# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files first to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install --production --ignore-scripts

# Copy the rest of the application code
COPY . .

# Expose default port if needed
# EXPOSE 3000

# Start the MCP server
CMD [ "npm", "start" ]
